# Generated by Django 5.2.8 on 2025-12-02 07:11

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 4), ('cta', 7)], blank=True, block_lookup={0: ('home.blocks.HeadingBlock', (), {}), 1: ('home.blocks.ParagraphBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {}), 6: ('wagtail.blocks.URLBlock', (), {}), 7: ('wagtail.blocks.StructBlock', [[('text', 5), ('button_text', 5), ('button_link', 6)]], {})}),
        ),
    ]
